// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAyvRbHK03z7FoeuoFV0Tlz_kwhAxsjL4',
    appId: '1:495921549869:android:7f1c985c82d0c87d915ea4',
    messagingSenderId: '495921549869',
    projectId: 'darzi-app-notification',
    storageBucket: 'darzi-app-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFYezYpgEp61_dhp1ePePuEwlT7ozCrW0',
    appId: '1:495921549869:ios:ecf86855ca6ba4b6915ea4',
    messagingSenderId: '495921549869',
    projectId: 'darzi-app-notification',
    storageBucket: 'darzi-app-notification.firebasestorage.app',
    iosBundleId: 'com.mannytech.darzi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFYezYpgEp61_dhp1ePePuEwlT7ozCrW0',
    appId: '1:495921549869:ios:067ae5925bb0ce09915ea4',
    messagingSenderId: '495921549869',
    projectId: 'darzi-app-notification',
    storageBucket: 'darzi-app-notification.firebasestorage.app',
    iosBundleId: 'com.bringle.darzi',
  );

}